"""Deterministic dummy execution scenarios for ORBIT.

The dummy engine exists to validate runtime structure before live model
integration. It produces named scenarios so event/state behavior can be tested
repeatably without provider randomness.
"""

from __future__ import annotations

from orbit.runtime.core.contracts import RunDescriptor
from orbit.runtime.execution.contracts.plans import ExecutionPlan, ToolRequest


class DummyEngine:
    """Provide deterministic execution plans for early ORBIT runtime work."""

    def plan(self, descriptor: RunDescriptor) -> ExecutionPlan:
        """Return the deterministic execution plan for a given scenario."""
        scenario = descriptor.dummy_scenario

        if scenario == "final_only":
            return ExecutionPlan(
                source_backend="dummy",
                plan_label=scenario,
                final_text="Dummy runtime completed without tool use.",
            )

        if scenario == "tool_then_finish":
            return ExecutionPlan(
                source_backend="dummy",
                plan_label=scenario,
                tool_request=ToolRequest(
                    tool_name="write_file",
                    input_payload={
                        "path": "notes/dummy-tool-then-finish.txt",
                        "content": "Generated by ORBIT dummy scenario: tool_then_finish\n",
                    },
                    requires_approval=True,
                    side_effect_class="write",
                ),
                final_text="Dummy runtime completed after a governed tool path.",
            )

        if scenario == "approval_required":
            return ExecutionPlan(
                source_backend="dummy",
                plan_label=scenario,
                tool_request=ToolRequest(
                    tool_name="write_file",
                    input_payload={
                        "path": "notes/dummy-approval-required.txt",
                        "content": "Generated by ORBIT dummy scenario: approval_required\n",
                    },
                    requires_approval=True,
                    side_effect_class="write",
                ),
                final_text="Dummy runtime would complete after approval-mediated execution.",
            )

        if scenario == "failure_case":
            return ExecutionPlan(
                source_backend="dummy",
                plan_label=scenario,
                failure_reason="Dummy scenario intentionally raised a runtime failure.",
            )

        raise ValueError(f"unknown dummy scenario: {scenario}")
