"""Shared adapter protocol for the runtime-first ORBIT terminal UI.

Both the mock adapter and the SessionManager-backed runtime adapter should
satisfy this protocol so the PTY CLI can switch from mock to real runtime
without changing render/handler/router logic.
"""

from __future__ import annotations

from typing import Any, Protocol

from .contracts import (
    InterfaceApproval,
    InterfaceArtifact,
    InterfaceEvent,
    InterfaceMessage,
    InterfaceSession,
    InterfaceToolCall,
)


class RuntimeCliAdapter(Protocol):
    def create_session(self, *, backend_name: str = ..., model: str | None = ...) -> InterfaceSession: ...

    def attach_session(self, session_id: str) -> InterfaceSession | None: ...

    def get_session(self, session_id: str) -> InterfaceSession | None: ...

    def list_sessions(self) -> list[InterfaceSession]: ...

    def list_messages(self, session_id: str) -> list[InterfaceMessage]: ...

    def list_events(self, session_id: str) -> list[InterfaceEvent]: ...

    def list_artifacts(self, session_id: str) -> list[InterfaceArtifact]: ...

    def list_tool_calls(self, session_id: str) -> list[InterfaceToolCall]: ...

    def list_open_approvals(self) -> list[InterfaceApproval]: ...

    def send_user_message(self, session_id: str, text: str, on_assistant_partial_text=None, on_stream_completed=None) -> list[InterfaceMessage]: ...

    def append_system_message(self, session_id: str, text: str, *, kind: str = ...) -> InterfaceMessage: ...

    def slash_help_text(self) -> str: ...

    def slash_help_page(self) -> str: ...

    def get_workbench_status(self) -> dict[str, Any]: ...

    def get_pending_approval(self, session_id: str) -> InterfaceApproval | None: ...

    def resolve_pending_approval(self, session_id: str, decision: str, note: str | None = ...) -> Any: ...

    def reauthorize_tool_path(self, session_id: str, tool_name: str, note: str | None = ..., source: str = ...) -> Any: ...

    def get_session_state_payload(self, session_id: str) -> dict[str, Any] | None: ...

    def append_context_artifact(self, session_id: str, artifact_type: str, content: str, source: str) -> Any: ...

    def clear_session(self, session_id: str) -> bool: ...

    def clear_all_sessions(self) -> bool: ...

    def wipe_session_history(self) -> bool: ...
